version: "3"

services:
  neo4j:
    image: neo4j:4.1.4
    container_name: neo4j
    network_mode: linking-net
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./${KG_DIR}:/var/lib/neo4j/data
      - ./output:/output
    environment:
      - NEO4J_AUTH=neo4j/jazero_admin
      - NEO4JLABS_PLUGINS='["apoc", "n10s"]'
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use_neo4j_config=false

networks:
  linking-net:
    name: "linking-net"
    external: true